name: hardhat test artifact

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_on_linux:
    name: Test on Ubuntu with Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18]
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"
      - name: Install
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Run tests
        run: pnpm test
      - name: Build
        run: pnpm build
      - name: Upload module directory
        uses: actions/upload-artifact@v3
        with:
          name: module-artifact
          path: ./dist # This uploads the entire repository as an artifact, you might want to specify just the module directory
